[versions]
# Plugins
shadow = "9.2.2"
resourceFactory = "1.3.1"
indra = "4.0.0"
runPaper = "3.0.2"
modPublishPlugin = "1.1.0"

# Dependencies
paper = "1.21.4-R0.1-SNAPSHOT"
paperTrail = "1.0.1"
legacyPluginBase = "0.0.1+161-SNAPSHOT"
bstats = "3.1.0"
cloudBom = "2.0.0"
cloudMinecraftBom = "2.0.0-beta.14"
cloudTranslationsBom = "1.0.0-SNAPSHOT"
interfacesPaper = "1.0.0-SNAPSHOT"
vaultApi = "1.7.1"
essentialsX = "2.21.2"
jspecify = "1.0.0"
worldGuard = "7.0.14"
worldEdit = "7.3.16"

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
resourceFactoryBukkit = { id = "xyz.jpenilla.resource-factory-bukkit-convention", version.ref = "resourceFactory" }
resourceFactoryPaper = { id = "xyz.jpenilla.resource-factory-paper-convention", version.ref = "resourceFactory" }
indra = { id = "net.kyori.indra", version.ref = "indra" }
indraGit = { id = "net.kyori.indra.git", version.ref = "indra" }
runPaper = { id = "xyz.jpenilla.run-paper", version.ref = "runPaper" }
modPublishPlugin = { id = "me.modmuss50.mod-publish-plugin", version.ref = "modPublishPlugin" }

[libraries]
# Compile Only
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
vaultApi = { module = "com.github.MilkBowl:VaultAPI", version.ref = "vaultApi" }
essentialsX = { module = "net.essentialsx:EssentialsX", version.ref = "essentialsX" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }
worldguard-bukkit = { module = "com.sk89q.worldguard:worldguard-bukkit", version.ref = "worldGuard" }
worldguard-core = { module = "com.sk89q.worldguard:worldguard-core", version.ref = "worldGuard" }
worldedit-bukkit = { module = "com.sk89q.worldedit:worldedit-bukkit", version.ref = "worldEdit" }
worldedit-core = { module = "com.sk89q.worldedit:worldedit-core", version.ref = "worldEdit" }

# Implementation
paper-trail = { module = "io.papermc:paper-trail", version.ref = "paperTrail" }
legacy-plugin-base = { module = "xyz.jpenilla:legacy-plugin-base", version.ref = "legacyPluginBase" }
bstats-bukkit = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }

# Cloud
cloud-bom = { module = "org.incendo:cloud-bom", version.ref = "cloudBom" }
cloud-minecraft-bom = { module = "org.incendo:cloud-minecraft-bom", version.ref = "cloudMinecraftBom" }
cloud-paper = { module = "org.incendo:cloud-paper" }
cloud-minecraft-extras = { module = "org.incendo:cloud-minecraft-extras" }
cloud-translations-bom = { module = "org.incendo:cloud-translations-bom", version.ref = "cloudTranslationsBom" }
cloud-translations-bukkit = { module = "org.incendo:cloud-translations-bukkit" }
cloud-translations-minecraft-extras = { module = "org.incendo:cloud-translations-minecraft-extras" }

# Interfaces
interfaces-paper = { module = "org.incendo.interfaces:interfaces-paper", version.ref = "interfacesPaper" }

